/*
!!! ATTENTION !!!
THIS FILE HAS BEEN AUTO-GENERATED
DO NOT EDIT THIS FILE
*/

// Imports 
import { AppConfig, api as axios } from '@config/ceoelevator-config'; 
import { ApiService } from '@services/ApiService';

// Custom Types 
type Guid = string; 
type Double = number; 
type Decimal = number; 
type DecimalNullable = number | null; 
type Int64 = number; 
type Int32 = number; 
type int = number; 
type long = number;

// Settings...

export namespace IAMAPI {

	export namespace Enums {

		export enum UserPushPlatform {
			Expo = 0,
			Firebase = 1,
			OneSignal = 2,
			Apns = 3,
			WebPush = 4,
		}

		export enum XSortingDirection {
			Ascending = 0,
			Descending = 1,
		}

		export enum UserSources {
			Manual = 0,
			Google = 1,
			Apple = 2,
			Unknown = 3,
		}

		export enum ClientPlatforms {
			Web = 0,
			Mobile = 1,
			Service = 2,
			Unknown = 3,
		}

	}

	export namespace Push {

		export namespace RegisterToken {
			export const RequestPath = AppConfig.IAMUrl + '/Push/RegisterToken';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				pushToken: string;
				deviceId: string;
				appName: string;
				platform: Enums.UserPushPlatform;
			}
			export interface IResponseModel {
				success: boolean;
			}
		}

	}

	export namespace MobilApplicationVersiyon {

		export namespace GetVersion {
			export const RequestPath = AppConfig.IAMUrl + '/MobilApplicationVersiyon/GetVersion';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				companyId: Guid;
				platform: string;
			}
			export interface IResponseModel {
				minVersion: string;
				latestVersion: string;
				forceUpdate: boolean;
				updateMessage: string;
				storeUrl: string;
			}
		}

	}

	export namespace User {

		export namespace Delete {
			export const RequestPath = AppConfig.IAMUrl + '/User/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

	}

	export namespace Users {

		export namespace Detail {
			export const RequestPath = AppConfig.IAMUrl + '/Users/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				companyId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				userName: string;
				email: string;
				fullName: string;
				language: string;
				isActive: boolean;
				isAvailable: boolean;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				isPhoneVerified: boolean;
				companyName: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.IAMUrl + '/Users/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				companyId: Guid;
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				userId: Guid;
				userName: string;
				email: string;
				fullName: string;
				isActive: boolean;
				isAvailable: boolean;
				phoneNumber: string;
				bucketId: string;
				roles: string[];
			}
		}

		export namespace UpdatePassword {
			export const RequestPath = AppConfig.IAMUrl + '/Users/UpdatePassword';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				oldPassword: string;
				newPassword: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace ResetPassword {
			export const RequestPath = AppConfig.IAMUrl + '/Users/ResetPassword';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				token: string;
				newPassword: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace ForgotPassword {
			export const RequestPath = AppConfig.IAMUrl + '/Users/ForgotPassword';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				email: string;
				companyId: Guid;
			}
			export interface IResponseModel {
				userId: Guid;
				email: string;
				tokenExpiry?: Date;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.IAMUrl + '/Users/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userName: string;
				firstName: string;
				surname: string;
				email: string;
				password: string;
				providerId: string;
				companyId: Guid;
				userSource: Enums.UserSources;
				description: string;
				phoneNumber: string;
			}
			export interface IResponseModel {
				id: Guid;
				userName: string;
				email: string;
				firstName: string;
				surname: string;
				isActive: boolean;
			}
		}

	}

	export namespace UserPermissions {

		export namespace My {
			export const RequestPath = AppConfig.IAMUrl + '/UserPermissions/My';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				permissions: string[];
				resources: IResourceModel[];
			}
			export interface IResourceModel {
				namespace: string;
				name: string;
				title: string;
			}
		}

	}

	export namespace Roles {

		export namespace All {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				isDeleted: boolean;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.IAMUrl + '/Roles/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
				companyId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Provinces {

		export namespace All {
			export const RequestPath = AppConfig.IAMUrl + '/Provinces/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				keyword: string;
			}
			export interface IResponseModel {
				id: number;
				name: string;
				code: string;
			}
		}

	}

	export namespace Neighborhoods {

		export namespace ByDistrict {
			export const RequestPath = AppConfig.IAMUrl + '/Neighborhoods/ByDistrict';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				districtId: number;
				keyword: string;
			}
			export interface IResponseModel {
				id: number;
				name: string;
				districtId: number;
				postalCode: string;
			}
		}

	}

	export namespace Districts {

		export namespace ByProvince {
			export const RequestPath = AppConfig.IAMUrl + '/Districts/ByProvince';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				provinceId: number;
				keyword: string;
			}
			export interface IResponseModel {
				id: number;
				name: string;
				provinceId: number;
			}
		}

	}

	export namespace Companies {

		export namespace Pick {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				isDeleted: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.IAMUrl + '/Companies/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				name: string;
				taxNumber: string;
				address: string;
				phone: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Auth {

		export namespace VerifyOtp {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/VerifyOtp';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				phoneNumber: string;
				companyId: Guid;
				otpCode: string;
			}
			export interface IResponseModel {
				isSuccess: boolean;
			}
		}

		export namespace SendOtp {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/SendOtp';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				phoneNumber: string;
				companyId: Guid;
				language: string;
			}
			export interface IResponseModel {
				isSuccess: boolean;
				otpCode: string;
			}
		}

		export namespace RevokeRefreshToken {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/RevokeRefreshToken';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				refreshTokenId: Guid;
			}
			export interface IResponseModel {
				success: boolean;
			}
		}

		export namespace RefreshToken {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/RefreshToken';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				refreshToken: string;
				platform: Enums.ClientPlatforms;
			}
			export interface IResponseModel {
				jwt: string;
				sessionExpirationDate: Date;
				refreshToken: string;
			}
		}

		export namespace Logout {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/Logout';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
			}
			export interface IResponseModel {
				messageCode: string;
			}
		}

		export namespace Login {
			export const RequestPath = AppConfig.IAMUrl + '/Auth/Login';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				provider: string;
				userName: string;
				password: string;
				token: string;
				platform: Enums.ClientPlatforms;
				isCompanyHolding: boolean;
				companyId: Guid;
				firstName: string;
				surname: string;
				phoneNumber: string;
				birthDate?: Date;
				externalProviderUserId: string;
			}
			export interface IResponseModel {
				jwt: string;
				refreshToken: string;
				sessionExpirationDate: Date;
				user: IUserResponse;
			}
			export interface IUserResponse {
				id: Guid;
				username: string;
				displayName: string;
				email: string;
				companyId: Guid;
				isCompanyHolding: boolean;
				companyName: string;
				isPhoneVerified: boolean;
			}
		}

	}

}